# Generated by Django 4.2.7 on 2024-03-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_blog_delete_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
